### ISSUE TITLE
Not sure if this belongs to CHP but a hybrid CHP

### ISSUE THREAD

**Issue by Aiena-g** [zeffii/mesh_tinyCAD_CHP#2]
Iwas wondering if we could extend CHP with a fillet/extend feature. The extend feature is the closest sane case to the T and X cases without making it insanely hard to implement. 

If we extend we can do a trim inn blender by just deleting an edge. I thing extend between 2 edges is more useful and CAD like than EXM.

I was testing this addon http://blenderartists.org/forum/showthread.php?338249-Addon-Smart-Edges-Intersect-Tool-%28can-keep-faces%29 it is good. But it misses something I like about CHP. It extends edges directly to the end point instead of preserving original vertex position and making a new edge. 

The difference between the 2 modes of CHP we had discussed earlier in another issue.

Wondering if you could integrate this code with your addon or make a more refined TC way of extending.

This kind of extension fits more with the general flow of how blender operates and is less disruptive than EXM.

I use your CHP addon regularly its a real help.

**Comment by zeffii** [comment]
hey, i'll say straight up I don't have much time for this at the moment. but you can spike my interest if you can draw me some images of the steps.  (don't need to be artworks..)

  1 ) before . 
  2 ) step 1...n
  3 ) finish

just a recap for myself here:
- CHP expects a V situation, 
- a T version of CHP (extend towards) isn't hard, (same complexity as X I predict) -- however T and X versions must somehow notify the algorithm which edges to Fillet..

**Comment by zeffii** [comment]
mesh_TinyCAD is designed to not care about faces. The scenarios where I use the add-on never involve faces, or remaking the few faces isn't a big deal. There is no incentive / reason for me to provide face-retention there..(at the moment I have no time..)

There's a [2D Boolean](https://github.com/zeffii/some_test_addon/blob/master/included_addons/boolean_2d_union.py) also by nixy (iirc), similar to EXM (it preserves faces) but has other limitations

**Comment by Aiena-g** [comment]
I do not want face retention. Just a similar kind of extend but keeping original vertex position. I think that fits in with general design of TC.

**Comment by Aiena-g** [comment]
Also face retention in this scenario would involve additional cleanup.

**Comment by Aiena-g** [comment]
If CHP cannot chamfer let it pick this mode. For the T or X case automatically.

**Comment by zeffii** [comment]
please make images. I find it sometimes difficult to interpret words ( show verts + edges )

**Comment by Aiena-g** [comment]
Ok basically this is how it works

1) Select an edge
2) select a second edge which does not meet.
3) Run CHP if it is a V case do the normal CHP operation else create a new segment so that one line meets the other and make a point in between.
Constraints:
 1) the second selected edge becomes the active edge 
2) it should extend the first selected edge to the last selected edge. 
3) No more than 2 edges can be selected at a time.

![feature request](https://cloud.githubusercontent.com/assets/5725991/12945072/23c692a6-d011-11e5-82b9-e41270eb05a6.jpg)

**Comment by Aiena-g** [comment]
this will also indirectly facilitate the T and X cases in blender because all the user then needs to do is simply delete the edge on the side they do not want.

**Comment by Aiena-g** [comment]
Note: image on the right is result of the operation. Forgot to mention that in the graphic.

**Comment by zeffii** [comment]
isn't that what VTX does already. that's the T case. -- it automatically picks V, T or X.

**Comment by Aiena-g** [comment]
(; Sorry didnt know VTX worked that way thought it just did something like XAll
